#!/usr/bin/python3

from uk_covid19 import Cov19API

cases_and_deaths = {
    "date": "date",
    "newCasesByPublishDate": "newCasesByPublishDate",
    "cumCasesByPublishDate": "cumCasesByPublishDate",
    "newDeaths28DaysByPublishDate": "newDeaths28DaysByPublishDate",
    "cumDeaths28DaysByPublishDate": "cumDeaths28DaysByPublishDate"
}

uk = [
    'areaType=overview',
]

api = Cov19API(filters=uk, structure=cases_and_deaths)
data = api.get_json()

deaths_today = data['data'][0]['newDeaths28DaysByPublishDate']
deaths_yesterday = data['data'][1]['newDeaths28DaysByPublishDate']

print(f"{deaths_today} ({deaths_today-deaths_yesterday})")
