#!/usr/bin/python3

from uk_covid19 import Cov19API

cases_and_deaths = {
    "date": "date",
    "newCasesByPublishDate": "newCasesByPublishDate",
    "cumCasesByPublishDate": "cumCasesByPublishDate",
    "newDeaths28DaysByPublishDate": "newDeaths28DaysByPublishDate",
    "cumDeaths28DaysByPublishDate": "cumDeaths28DaysByPublishDate"
}

uk = [
    'areaType=overview',
]

api = Cov19API(filters=uk, structure=cases_and_deaths)
data = api.get_json()

cases_today = data['data'][0]['newCasesByPublishDate']
cases_yesterday = data['data'][1]['newCasesByPublishDate']

change = cases_today - cases_yesterday
percent_increase = (change * 1.0 / cases_yesterday) * 100
percent_increase = round(percent_increase, 2) 

sign = ""

if change > 0:
    sign = "+"
elif change < 0:
    sign = "-"

print(f"{cases_today} | {sign}{change} | {sign}{percent_increase}%")
