#!/usr/bin/python3
import PyDictionary
import sys
import pyperclip

definitions = PyDictionary.PyDictionary().meaning(sys.argv[1])

clip = [sys.argv[1]]
for value in definitions.values():
    for defn in value:
        clip.append(defn)

pyperclip.copy("\n".join(clip))
