#!/bin/bash

data=$(curl --no-progress-meter https://corona-stats.online/UK | 
        grep "UK" |
        sed "s/\s*//g ; s/║//g ; s/,//g ; s/▲//g ; s/│/;/g" |
        sed -e "s/\x1b\[.\{1,5\}m//g")

echo $data > ~/rona-data-temp
newcases=$(echo $data | cut -d";" -f 4)
[ -n $newcases ] && [ -n "$(diff -N ~/rona-data-temp ~/rona-data-today)" ] && (mv ~/rona-data-today ~/rona-data-yesterday & mv ~/rona-data-temp ~/rona-data-today)
