#!/bin/bash

[ "$USER" == "dolica" ] && (quiterss & bluemail & exit)

DOW=$(date +%u)
HOUR=$(date +"%H")
[[ $HOUR < 19 ]] && (( $DOW < 6 )) && [ "$USER" == "work" ] && WORKTIME=1

((WORKTIME)) && i3-msg 'workspace music; append_layout ~/.config/i3/music.json'
((WORKTIME)) && (teams & slack & riot-web & webmail & shortwave)
