#!/usr/bin/python
import sys
import pyperclip

input_url = sys.argv[1]
pyperclip.copy(
    "https://www.youtube.com/feeds/videos.xml?channel_id=" + input_url.split("/")[-1]
)
print("Copied feed URL to clipboard.")
